backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# 1. FORCE DECAP TO USE LOCAL RELATIVE PATHS FOR PREVIEWS
media_folder: "src/assets/images"
public_folder: "/src/assets/images"
media_folder_relative: true # Enables relative paths globally
# publish_mode: editorial_workflow

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/articles
    label: "Articles" # Used in the UI
    folder: "src/content/articles" # The path to the folder where the documents are stored
    create:
      true # Allow users to create new documents in this collection
      # Use relative paths so images are saved in the specific blog post folder
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index" # Use relative paths so images are saved in the specific blog post folder
    fields: # The fields for each document, usually in frontmatter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "src/layouts/BlogPostLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Ranking",
          name: "ranking",
          widget: "number",
          value_type: "float",
        }
      - { label: "Post Image", name: "hero", widget: "image" }
      - { label: "Image Caption", name: "caption", widget: "string" }
      - { label: "Articles Page Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["articles"] }
      - { label: "Body", name: "body", widget: "markdown" }
    sortable_fields: ["title", "ranking", "tags"]
